version: "3.9"

services:

  frontend:
    build: frontend/
    restart_policy:
      condition: on-failure
    ports:
      - "3000:3000"

  backend:
    build: backend/
    restart_policy:
      condition: on-failure
    ports:
      - "4000:4000"
