kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  #
  # The frontend doesn't use many resources to serve static JS + CSS from an nginx container, so this is less about
  # performance and more about redundancy.
  #
  replicas: 2

  #
  # Whenever k8s decides to create one or more pod for this deployment, it will use the YAML here to form
  # the contents of the pods resource definition YAML.
  #
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pserwylo/cognizant-k8s-pres-frontend:latest
          ports:
            - containerPort: 8080
