kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
data:
  #
  # We will ask kubernetes to create a volume based on the contents of this config map, which we can then mount
  # into our containers. Each entry in this "data:" block will be written to a file in this virtual volume.
  #
  config.json: |
    {
      "environment": "production",
      "dbConnection": "mongodb+srv://c7t-k8s:woecsle38cy2@prod-mongo.enterprise-host.com/c7t-k8s?retryWrites=true&w=majority"
    }
